### ISSUE TITLE
Does not work with .NET 5

### ISSUE THREAD

**Issue by groogiam** [unoplatform/Uno.SQLitePCLRaw.Wasm#19]
Attempting to use the sample with .NET 5 (repro attached) results in the following error.
[SqliteWasm.zip](https://github.com/unoplatform/Uno.SQLitePCLRaw.Wasm/files/6099302/SqliteWasm.zip)

```
uno-bootstrap.js:201 Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at :44378/SQLitePCL.SQLite3Provider_dynamic_cdecl.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(:44378/ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(:44378/String name, Int32 flags)
   at :44378/SQLitePCL.Batteries_V2.Init()
   at :44378/SQLitePCL.Batteries.Init()
   at SqliteWasm.Program.Main(:44378/String[] args)
    at Object.call_method (uno-bootstrap.js:157)
    at Object.mainInit (uno-bootstrap.js:198)
    at Object.initializeRequire (uno-bootstrap.js:479)
    at Object.init (uno-bootstrap.js:172)
    at Object.loaded_cb (uno-bootstrap.js:38)
    at Object._finalize_startup (dotnet.js:1)
    at onPendingRequestComplete (dotnet.js:1)
    at processFetchResponseBuffer (dotnet.js:1)
```

**Comment by groogiam** [comment]
@jeromelaban Is there any update on this issue. The same issue still persists with Uno.Wasm.Bootstrap 3.0.0-dev.95? Thanks.

**Comment by jeromelaban** [comment]
There's been progress on this issue for .NET 5, but it's not working fully yet.

The reason it's not progressing is caused by [this block](https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs#L152-L155), which in turn invokes [this from Sqlite PCL Raw](https://github.com/ericsink/SQLitePCL.raw/blob/1b2e50535cf3c3e4811197b72b7dc694715227f6/src/providers/provider.tt#L837).

The reason it fails is because this is a P/Invoke callback that is not recognized by the .NET runtime tooling, which can be either via UnmanagedCallersOnly (as it is done [in the runtime](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/Globalization/CalendarData.Icu.cs#L431)). 

The problem here is that Sqlite PCL Raw is netstandard2.0-built, which cannot reference UnmanagedCallersOnly as it is .NET 5 or later.

One possible solution would be to add support for something like this to the Uno boostrapper:

```xml
<ItemGroup>
  <WasmShellPInvokeCallbackSignature Include="SQLitePCL.SQLite3Provider_sqlite3:scalar_function_hook_bridge_impl"/>
</ItemGroup>
```

For reference, here's the runtime failure:

```
Assertion: should not be reached at D:/a/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/mono/mono/mini/mini.c:4345
_emscripten_asm_const_int    @    dotnet.js:6396
$wasm_trace_logger    @    0144754e:0x398132
$eglib_log_adapter    @    0144754e:0x268030
$monoeg_g_logstr    @    0144754e:0x2b9c85
$monoeg_g_logv_nofree    @    0144754e:0x2b9c29
$monoeg_assertion_message    @    0144754e:0x2b9d06
$mono_assertion_message_unreachable    @    0144754e:0x2b9d78
$mini_method_compile    @    0144754e:0x28a87e
$mono_jit_compile_method_inner    @    0144754e:0x28a86c
$mono_jit_compile_method_with_opt    @    0144754e:0x28bbec
$mono_jit_compile_method    @    0144754e:0x28b7d1
$mono_compile_method_checked    @    0144754e:0x23f912
$mono_delegate_to_ftnptr_impl    @    0144754e:0x22b724
$mono_delegate_to_ftnptr    @    0144754e:0x223452
$do_icall    @    0144754e:0x1d8a91
$do_icall_wrapper    @    0144754e:0x1d7f70
$interp_exec_method    @    0144754e:0x1d4432
$interp_runtime_invoke    @    0144754e:0x1c8c99
$mono_jit_runtime_invoke    @    0144754e:0x28d334
$do_runtime_invoke    @    0144754e:0x23e83f
$mono_runtime_invoke_checked    @    0144754e:0x23e7ce
$mono_runtime_try_invoke_array    @    0144754e:0x242ef3
$mono_runtime_invoke_array_checked    @    0144754e:0x243581
$ves_icall_InternalInvoke    @    0144754e:0x217e02
$ves_icall_InternalInvoke_raw    @    0144754e:0x21fa3e
$do_icall    @    0144754e:0x1d8b4e
$do_icall_wrapper    @    0144754e:0x1d7f70
$interp_exec_method    @    0144754e:0x1c9d9e
$interp_runtime_invoke    @    0144754e:0x1c8c99
```

**Comment by jeromelaban** [comment]
Opened https://github.com/ericsink/SQLitePCL.raw/issues/423 in SQLitePCL.raw

**Comment by jeromelaban** [comment]
Fixed in #21

**Comment by groogiam** [comment]
@jeromelaban I still cannot get this to work. I have update all the nuget packages and the framework to .NET6 and now when I run the repro it cannot find the provider. 
[SqliteWasm6.zip](https://github.com/unoplatform/Uno.SQLitePCLRaw.Wasm/files/7585431/SqliteWasm6.zip)

```
uno-bootstrap.js:204 Error: System.DllNotFoundException: e_sqlite3
   at :5001/SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(:5001/ISQLite3Provider imp)
   at :5001/SQLitePCL.Batteries_V2.Init()
   at :5001/SQLitePCL.Batteries.Init()
   at SqliteWasm.Program.Main(:5001/String[] args)
    at Object.call_method (uno-bootstrap.js:157)
    at Object.mainInit (uno-bootstrap.js:198)
    at Object.initializeRequire (uno-bootstrap.js:483)
    at Object.init (uno-bootstrap.js:172)
    at Object.loaded_cb (uno-bootstrap.js:38)
    at Object._finalize_startup (dotnet.js:1)
    at onPendingRequestComplete (dotnet.js:1)
    at processFetchResponseBuffer (dotnet.js:1)
mainInit @ uno-bootstrap.js:204
```

**Comment by groogiam** [comment]
I was able to get this working based in guidance received on this issue. https://github.com/unoplatform/Uno.Samples/issues/81
